### ISSUE TITLE
Converter roadmap

### ISSUE THREAD

**Issue by Remi-Gau** [mszinte/bids-specification#4]
- input format: aim first for the eyetracker that occupy the biggest share of the market
  - eyelink
  - tobii
- allow conversion from from BIDS "legacy" format `_recording-eyetracking_physio.tsv.gz`
- usable as a library and as a bidscoin plugin
- use opensource datasets as test input files

**Comment by Remi-Gau** [comment]
- [x] build container for converter : start from bidsphysio and adapt it
- [x] test pyedfread: https://github.com/nwilming/pyedfread
  - [x] see what it does: inputs, outputs...
- [x] from EDF --> tsv + json broken down in:
  - [x] from EDF --> ascii --> tsv
  - [x] from EDF --> ascii --> json

**Comment by julia-pfarr** [comment]
### Output of [bidsphysio](https://github.com/cbinyu/bidsphysio/blob/master/bidsphysio.edf2bids/bidsphysio/edf2bids/edf2bidsphysio.py):


> * [ ]  from EDF --> tsv + json broken down in:
>   
>   * [ ]  from EDF --> ascii --> tsv

    "Columns": [
        "samples",
        "gx_left",
        "gy_left",
        "pa_left",
        "fixation",
        "saccade",
        "blink"
    ],

Comparison [BEP020](https://bids.neuroimaging.io/bep020) to output [bidsphysio](https://github.com/cbinyu/bidsphysio/blob/master/bidsphysio.edf2bids/bidsphysio/edf2bids/edf2bidsphysio.py):

- [eye_timestamp](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye_timestamp) is saved in another tsv file named _events.tsv (first column)
- [eye1_x_coordinate](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye1_x_coordinate)/ [eye2_x_coordinate](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye2_x_coordinate) equals "gx_left/right"
- [eye1_y_coordinate](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye1_y_coordinate)/ [eye2_y_coordinate](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye2_y_coordinate) equals "gy_left/right"
- [eye1_pupil_size](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye1_pupil_size)/ [eye2_pupil_size](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.columns.eye2_pupil_size) equals "pa_left/right"



>   * [ ]  from EDF --> ascii --> json




    "Columns": [
        "samples",
        "gx_left",
        "gy_left",
        "pa_left",
        "fixation",
        "saccade",
        "blink"
    ],
    "RecordedEye": "Left",
    "SamplingFrequency": 1000,
    "StartTime": 0.0

Missing in json by bidsphysio:

- [EnvironmentCoordinates](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.EnvironmentCoordinates)
- [SampleCoordinateUnit](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.SampleCoordinateUnits)
- [SampleCoordinateSystem](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.SampleCoordinateSystem)
- [Manufacturer](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.Manufacturer)
- [ManufacturersModelName](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.ManufacturersModelName)
- [SoftwareVersions](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.SoftwareVersions)
- [DeviceSerialNumber](https://bids-specification--1128.org.readthedocs.build/en/1128/glossary.html#objects.metadata.DeviceSerialNumber)
- **!!Does not output an additional _events.json file!!** --> missing
- all other optional [Recommended fields](https://bids-specification--1128.org.readthedocs.build/en/1128/modality-specific-files/eye-tracking.html#recommended-fields)

**Comment by julia-pfarr** [comment]
Differentiation [pyedfread](https://github.com/nwilming/pyedfread) and bidsphysio: pyedfread only makes edf files readable, bidsphysio code decides what to extract from it for bids

**Comment by Remi-Gau** [comment]
Makes me realize that we got eye1 and eye2 but we do not specify how to know which eye is the right one and which one is the left when both are recorded.

**Comment by Remi-Gau** [comment]
Another thought.
Given that bidsphysio gives the typical output for what will be the typical "legacy" eyetracking format (the one that is recommended in the spec at the moment), the things you did highlighted @julia-pfarr will help us flag missing metadata to the user when converting from legacy to BEP20 valid output.
